#!/bin/bash

# 🚀 GUÍA DE DESPLIEGUE - AAC COMUNICADOR

echo "======================================"
echo "🎯 AAC COMUNICADOR - DEPLOYMENT GUIDE"
echo "======================================"
echo ""

echo "📦 PASO 1: Instalar Firebase CLI (si no lo tienes)"
echo "   npm install -g firebase-tools"
echo ""

echo "🔐 PASO 2: Login en Firebase"
echo "   firebase login"
echo ""

echo "🏗️  PASO 3: Inicializar Firebase (si no está inicializado)"
echo "   firebase init hosting"
echo "   - Selecciona tu proyecto existente o crea uno nuevo"
echo "   - Public directory: dist"
echo "   - Single-page app: Yes"
echo "   - Automatic builds: No"
echo ""

echo "🔨 PASO 4: Build de producción"
echo "   npm run build"
echo ""

echo "🚀 PASO 5: Deploy a Firebase Hosting"
echo "   firebase deploy --only hosting"
echo ""

echo "✅ PASO 6: Tu app estará en:"
echo "   https://tu-proyecto.web.app"
echo "   https://tu-proyecto.firebaseapp.com"
echo ""

echo "======================================"
echo "📱 CARACTERÍSTICAS IMPLEMENTADAS:"
echo "======================================"
echo "✅ Construcción de frases"
echo "✅ Categorías visuales (Necesidades, Emociones, Comida, Actividades)"
echo "✅ Modo oscuro"
echo "✅ Selector de voz (Hombre/Mujer)"
echo "✅ Modo escáner (accesibilidad)"
echo "✅ Animaciones y haptic feedback"
echo "✅ PWA (funciona como app móvil)"
echo "✅ Sistema de perfiles de usuario"
echo "✅ Integración ARASAAC"
echo ""

echo "======================================"
echo "🎨 COMANDOS ÚTILES:"
echo "======================================"
echo "Desarrollo local:"
echo "   npm run dev"
echo ""
echo "Build:"
echo "   npm run build"
echo ""
echo "Preview build:"
echo "   npm run preview"
echo ""
echo "Deploy:"
echo "   firebase deploy"
echo ""
echo "Ver logs:"
echo "   firebase hosting:channel:list"
echo ""
